// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3SHLu98bcEHraf9x_xZrubS5bBDTZbhg',
    appId: '1:558737185486:web:1822d13d6d1b9ada5ace9f',
    messagingSenderId: '558737185486',
    projectId: 'authentication-system-d584b',
    authDomain: 'authentication-system-d584b.firebaseapp.com',
    storageBucket: 'authentication-system-d584b.appspot.com',
    measurementId: 'G-2PJPWBLBZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCMACrf9XmHoIiBeABE678vCDO8COrV_c',
    appId: '1:558737185486:android:2abc9d91189a0d0f5ace9f',
    messagingSenderId: '558737185486',
    projectId: 'authentication-system-d584b',
    storageBucket: 'authentication-system-d584b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEH6fphIcwgy3YCQBoGEvlAa86puUTCF4',
    appId: '1:558737185486:ios:951988ebcc77f0855ace9f',
    messagingSenderId: '558737185486',
    projectId: 'authentication-system-d584b',
    storageBucket: 'authentication-system-d584b.appspot.com',
    androidClientId: '558737185486-qelr1vr16k71an0va57kbb5srdfdp9mh.apps.googleusercontent.com',
    iosClientId: '558737185486-go8s4isd7bkhl8inp51uscumq1ed1d8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEH6fphIcwgy3YCQBoGEvlAa86puUTCF4',
    appId: '1:558737185486:ios:951988ebcc77f0855ace9f',
    messagingSenderId: '558737185486',
    projectId: 'authentication-system-d584b',
    storageBucket: 'authentication-system-d584b.appspot.com',
    androidClientId: '558737185486-qelr1vr16k71an0va57kbb5srdfdp9mh.apps.googleusercontent.com',
    iosClientId: '558737185486-go8s4isd7bkhl8inp51uscumq1ed1d8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
