// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCMACrf9XmHoIiBeABE678vCDO8COrV_c',
    appId: '1:558737185486:android:707ff57e77843a165ace9f',
    messagingSenderId: '558737185486',
    projectId: 'authentication-system-d584b',
    storageBucket: 'authentication-system-d584b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEH6fphIcwgy3YCQBoGEvlAa86puUTCF4',
    appId: '1:558737185486:ios:f0a6604b108c11345ace9f',
    messagingSenderId: '558737185486',
    projectId: 'authentication-system-d584b',
    storageBucket: 'authentication-system-d584b.appspot.com',
    androidClientId: '558737185486-3i8d63a6ufvhljvlq661sm28r1bf7m9i.apps.googleusercontent.com',
    iosClientId: '558737185486-754cvktqvmn6b9d72fsduc3rn689nvqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newDriver',
  );
}
